# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1398, 915)
        MainWindow.setStyleSheet("background-color: #d7dfe0;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.set_image_database_path_btn = QtWidgets.QPushButton(self.centralwidget)
        self.set_image_database_path_btn.setGeometry(QtCore.QRect(10, 10, 201, 61))
        self.set_image_database_path_btn.setStyleSheet("QPushButton { background-color: #329ba8 };")
        self.set_image_database_path_btn.setObjectName("set_image_database_path_btn")
        self.search_folder_recursively_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.search_folder_recursively_checkbox.setGeometry(QtCore.QRect(40, 80, 141, 31))
        self.search_folder_recursively_checkbox.setObjectName("search_folder_recursively_checkbox")
        self.image_db_label = QtWidgets.QLabel(self.centralwidget)
        self.image_db_label.setGeometry(QtCore.QRect(230, 10, 311, 51))
        self.image_db_label.setWordWrap(True)
        self.image_db_label.setObjectName("image_db_label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(560, 60, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(560, 80, 101, 16))
        self.label_3.setObjectName("label_3")
        self.sub_image_width_input = QtWidgets.QLineEdit(self.centralwidget)
        self.sub_image_width_input.setGeometry(QtCore.QRect(660, 60, 113, 20))
        self.sub_image_width_input.setStyleSheet("QLineEdit { background-color: white };")
        self.sub_image_width_input.setObjectName("sub_image_width_input")
        self.sub_image_heigt_input = QtWidgets.QLineEdit(self.centralwidget)
        self.sub_image_heigt_input.setGeometry(QtCore.QRect(660, 80, 113, 20))
        self.sub_image_heigt_input.setStyleSheet("QLineEdit { background-color: white };")
        self.sub_image_heigt_input.setObjectName("sub_image_heigt_input")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(560, 0, 261, 51))
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(880, 60, 101, 16))
        self.label_6.setObjectName("label_6")
        self.images_per_row = QtWidgets.QLineEdit(self.centralwidget)
        self.images_per_row.setGeometry(QtCore.QRect(980, 60, 113, 20))
        self.images_per_row.setStyleSheet("QLineEdit { background-color: white };")
        self.images_per_row.setObjectName("images_per_row")
        self.do_not_reuse_subimages_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.do_not_reuse_subimages_checkbox.setGeometry(QtCore.QRect(40, 520, 141, 31))
        self.do_not_reuse_subimages_checkbox.setObjectName("do_not_reuse_subimages_checkbox")
        self.save_image_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_image_btn.setGeometry(QtCore.QRect(10, 660, 201, 61))
        self.save_image_btn.setStyleSheet("QPushButton { background-color: #329ba8 };")
        self.save_image_btn.setObjectName("save_image_btn")
        self.convert_and_index_btn = QtWidgets.QPushButton(self.centralwidget)
        self.convert_and_index_btn.setGeometry(QtCore.QRect(10, 120, 201, 61))
        self.convert_and_index_btn.setStyleSheet("QPushButton { background-color: #329ba8 };")
        self.convert_and_index_btn.setObjectName("convert_and_index_btn")
        self.load_main_image_btn = QtWidgets.QPushButton(self.centralwidget)
        self.load_main_image_btn.setGeometry(QtCore.QRect(10, 330, 201, 61))
        self.load_main_image_btn.setStyleSheet("QPushButton { background-color: #329ba8 };")
        self.load_main_image_btn.setObjectName("load_main_image_btn")
        self.show_random_converted_image_btn = QtWidgets.QPushButton(self.centralwidget)
        self.show_random_converted_image_btn.setGeometry(QtCore.QRect(10, 230, 201, 61))
        self.show_random_converted_image_btn.setStyleSheet("QPushButton { background-color: #329ba8 };")
        self.show_random_converted_image_btn.setObjectName("show_random_converted_image_btn")
        self.img_label = QtWidgets.QLabel(self.centralwidget)
        self.img_label.setGeometry(QtCore.QRect(230, 110, 1161, 621))
        self.img_label.setStyleSheet("QLabel { \n"
"    background-color: white;\n"
"    border: 1px solid black;\n"
" };")
        self.img_label.setText("")
        self.img_label.setObjectName("img_label")
        self.progress_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_bar.setGeometry(QtCore.QRect(10, 740, 1371, 23))
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.feedback = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.feedback.setGeometry(QtCore.QRect(10, 770, 1371, 101))
        self.feedback.setStyleSheet("QPlainTextEdit { \n"
"    background-color: white;\n"
"    border: 1px solid black;\n"
" };")
        self.feedback.setObjectName("feedback")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(870, -10, 261, 51))
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 190, 91, 16))
        self.label_8.setObjectName("label_8")
        self.artify_main_image_btn = QtWidgets.QPushButton(self.centralwidget)
        self.artify_main_image_btn.setGeometry(QtCore.QRect(10, 450, 201, 61))
        self.artify_main_image_btn.setStyleSheet("QPushButton { background-color: #329ba8 };")
        self.artify_main_image_btn.setObjectName("artify_main_image_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1398, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.set_image_database_path_btn.setText(_translate("MainWindow", "set image database path"))
        self.search_folder_recursively_checkbox.setText(_translate("MainWindow", "search folder recursively"))
        self.image_db_label.setText(_translate("MainWindow", "Path: _"))
        self.label_2.setText(_translate("MainWindow", "SUB IMAGE WIDTH:"))
        self.label_3.setText(_translate("MainWindow", "SUB IMAGE HEIGHT:"))
        self.sub_image_width_input.setText(_translate("MainWindow", "281"))
        self.sub_image_heigt_input.setText(_translate("MainWindow", "500"))
        self.label_4.setText(_translate("MainWindow", "width and height every images will be converted to. The image will be scaled down later on according to the dimensions of the main image"))
        self.label_6.setText(_translate("MainWindow", "IMAGES PER ROW:"))
        self.images_per_row.setText(_translate("MainWindow", "60"))
        self.do_not_reuse_subimages_checkbox.setText(_translate("MainWindow", "do not reuse subimages"))
        self.save_image_btn.setText(_translate("MainWindow", "Save image"))
        self.convert_and_index_btn.setText(_translate("MainWindow", "Convert and index images"))
        self.load_main_image_btn.setText(_translate("MainWindow", "Load main image"))
        self.show_random_converted_image_btn.setText(_translate("MainWindow", "Show random converted image"))
        self.label_7.setText(_translate("MainWindow", "Amount of images user per row for the main image. The amount per column will be calculated accordingly"))
        self.label_8.setText(_translate("MainWindow", "Amount of images:"))
        self.artify_main_image_btn.setText(_translate("MainWindow", "Artify main image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
